[package]
name = "tictactoe"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
license = "MIT"           # e.g., "MIT", "GPL", "Apache 2.0"
authors = ["Kampter"]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
tictactoe = "0x0"


